server:
  port: 8082

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: 'gateway'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
